controller_manager:
  ros__parameters:
    update_rate: 30

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_footprint
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.1826
    wheel_radius: 0.0325
    use_stamped_vel: false
    enable_odom_tf: false

joint_state_broadcaster:
  ros__parameters: {}

imu_broadcaster:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: imu_link
    static_covariance_orientation: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    static_covariance_angular_velocity: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    static_covariance_linear_acceleration: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
